# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWHH6WdblD0bLM26aWaMz2LIcqHQdt0v
"""



import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Завантаження даних
data = np.loadtxt('/content/sample_data/data_singlevar_regr.txt', delimiter=',')
X = data[:, [0]]  # Альтернативний спосіб зробити стовпчиковий вектор
y = data[:, 1]

# Створення моделі
model = LinearRegression()
model.fit(X, y)

# Прогноз
predictions = model.predict(X)

# Метрики
print("Результати лінійної регресії:")
print(f"Коефіцієнт (нахил): {model.coef_[0]:.4f}")
print(f"Інтерсепт (зсув): {model.intercept_:.4f}")
print(f"Середньоквадратична помилка (MSE): {mean_squared_error(y, predictions):.4f}")
print(f"Коефіцієнт детермінації (R²): {r2_score(y, predictions):.4f}")

# Графік
plt.figure(figsize=(10, 6))
plt.scatter(X, y, c='blue', label='Справжні дані')
plt.plot(X, predictions, 'r-', linewidth=2, label='Лінія регресії')
plt.xlabel('Незалежна змінна (X)')
plt.ylabel('Залежна змінна (y)')
plt.title('Лінійна регресія для даних з data_singlevar_regr.txt')
plt.legend()
plt.grid(True)
plt.show()