# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Am6AvQTI5Oy59iSvY7_9sONYsvuSvldU
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Отримання медичних даних
dataset = load_diabetes()
inputs = dataset.data       # Вхідні параметри (ознаки)
outcomes = dataset.target   # Вихідна змінна (стан хвороби)

# Ініціалізація моделі
reg = LinearRegression()
reg.fit(inputs, outcomes)

# Прогнозування
estimations = reg.predict(inputs)

# Обчислення показників якості
score_r2 = r2_score(outcomes, estimations)
error_mae = mean_absolute_error(outcomes, estimations)
error_mse = mean_squared_error(outcomes, estimations)

# Вивід результатів
print(f"R²: {score_r2:.3f}")
print(f"MAE: {error_mae:.3f}")
print(f"MSE: {error_mse:.3f}")

# Візуалізація результатів
plt.figure(figsize=(10, 9))
plt.scatter(outcomes, estimations, alpha=0.5, label='Фактичні vs Прогнозовані')
plt.plot([outcomes.min(), outcomes.max()], [outcomes.min(), outcomes.max()], linestyle='--', color='black', linewidth=2, label='Лінія відповідності')
plt.xlabel('Реальні значення')
plt.ylabel('Оцінені значення')
plt.title('Оцінка прогресу захворювання за допомогою регресії')
plt.legend()
plt.grid(True)
plt.show()