# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13w4zz9M0R0yI6bwnmXGQBetrF8lGsnYr
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score

# Варіант 6: синусоїдальна залежність із шумом
num_points = 100
x_input = np.linspace(-3, 3, num_points).reshape(-1, 1)
random_shift = np.random.uniform(-0.6, 0.6, num_points).reshape(-1, 1)
y_output = 2 * np.sin(x_input) + random_shift

# Лінійна регресія
linear_model = LinearRegression()
linear_model.fit(x_input, y_output)
y_linear_pred = linear_model.predict(x_input)

# Поліноміальна регресія (ступінь 5)
poly_gen = PolynomialFeatures(degree=5, include_bias=False)
x_poly = poly_gen.fit_transform(x_input)
poly_model = LinearRegression()
poly_model.fit(x_poly, y_output)
y_poly_pred = poly_model.predict(x_poly)

# Метрики точності
mse_linear = mean_squared_error(y_output, y_linear_pred)
mse_poly = mean_squared_error(y_output, y_poly_pred)
r2_linear = r2_score(y_output, y_linear_pred)
r2_poly = r2_score(y_output, y_poly_pred)

# Виведення результатів
print("Оцінка лінійної моделі:")
print(f"MSE: {mse_linear:.3f}, R²: {r2_linear:.3f}")
print("\nОцінка поліноміальної моделі (ступінь 5):")
print(f"MSE: {mse_poly:.3f}, R²: {r2_poly:.3f}")

# Візуалізація
plt.figure(figsize=(12, 6))

# Графік для лінійної моделі
plt.subplot(1, 2, 1)
plt.scatter(x_input, y_output, color='navy', s=20, label='Спостереження')
plt.plot(x_input, y_linear_pred, color='firebrick', label='Лінійна модель')
plt.title('Лінійна апроксимація')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)

# Графік для поліноміальної моделі
plt.subplot(1, 2, 2)
sorted_indices = np.argsort(x_input[:, 0])
plt.scatter(x_input, y_output, color='navy', s=20, label='Спостереження')
plt.plot(x_input[sorted_indices], y_poly_pred[sorted_indices], color='forestgreen', label='Поліном ступеня 5')
plt.title('Поліноміальна апроксимація')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()