# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M1OKLYkZ0MBBbNNXLbGRsCx2F94yp9f
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Завантаження даних з твого варіанту
data = np.loadtxt('/content/sample_data/data_regr_1.txt', delimiter=',')
X = data[:, [0]]  # Незалежна змінна
y = data[:, 1]    # Залежна змінна

# Створення та тренування моделі
model = LinearRegression()
model.fit(X, y)

# Прогнозування
y_pred = model.predict(X)

# Обчислення метрик якості
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

# Виведення результатів
print("Результати лінійної регресії:")
print(f"Коефіцієнт (нахил): {model.coef_[0]:.4f}")
print(f"Інтерсепт (зсув): {model.intercept_:.4f}")
print(f"Середньоквадратична помилка (MSE): {mse:.4f}")
print(f"Коефіцієнт детермінації (R²): {r2:.4f}")

# Побудова графіка
plt.figure(figsize=(10, 6))
plt.scatter(X, y, color='blue', label='Справжні дані')
plt.plot(X, y_pred, color='red', linewidth=2, label='Лінія регресії')
plt.xlabel('Незалежна змінна (X)')
plt.ylabel('Залежна змінна (y)')
plt.title('Лінійна регресія для даних з data_regr_1.txt')
plt.legend()
plt.grid(True)
plt.show()