# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1vC4Fw9zqSTmYtd66U35ieyByeohivL
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Імпорт даних із локального джерела
raw_data = np.loadtxt('/content/sample_data/data_multivar_regr.txt', delimiter=',')

# Розділення на ознаки (features) і мітки (targets)
features = raw_data[:, :-1]
target = raw_data[:, -1]

# Ініціалізація та тренування регресора
regressor = LinearRegression()
regressor.fit(features, target)

# Прогнозування на основі навченої моделі
predicted = regressor.predict(features)

# Обчислення метрик точності
mse_val = mean_squared_error(target, predicted)
r2_val = r2_score(target, predicted)

# Вивід результатів
print("Підсумки моделі з кількома входами:")
print(f"Вагові коефіцієнти: {regressor.coef_}")
print(f"Зсув (intercept): {regressor.intercept_:.3f}")
print(f"Похибка (MSE): {mse_val:.3f}")
print(f"Наближеність (R²): {r2_val:.3f}")