# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1vC4Fw9zqSTmYtd66U35ieyByeohivL
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Твої експериментальні дані
X = np.array([3.33, 1, 63, 0.87, 0.42, 0.27]).reshape(-1, 1)
Y = np.array([0.48, 1.03, 2.02, 4.25, 7.16, 11.5])

# Створення та навчання моделі
model = LinearRegression()
model.fit(X, Y)

# Отримання коефіцієнтів
a = model.coef_[0]
b = model.intercept_
print(f"Апроксимуюча функція: Y = {a:.2f}X + {b:.2f}")

# Прогноз для побудови графіка
X_range = np.linspace(min(X), max(X), 100).reshape(-1, 1)
Y_pred = model.predict(X_range)

# Побудова графіка
plt.scatter(X, Y, color='red', label='Експериментальні точки')
plt.plot(X_range, Y_pred, color='blue', label=f'Y = {a:.2f}X + {b:.2f}')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Апроксимація методом найменших квадратів')
plt.legend()
plt.grid(True)
plt.show()